### ISSUE TITLE
Problem: Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by willschneider15** [acchampion/TicTacToeNew#1]
Fix, by replacing:

android:theme="@style/Theme.Splash"

on lines 36 and 61 in AndroidManifest.xml with: 

android:theme="@style/Theme.AppCompat.Light"

or update styles.xml

**Comment by acchampion** [comment]
I fixed this issue with commit https://github.com/acchampion/TicTacToeNew/commit/90ff834263ceded49e5d5820a3a5dc5d805cf1fc . Let me know if you have any other issues.
